version: '3.4'

services:
  aiinsole.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    image: chandimajay90/aiinsole-server
    build:
      context: .
      dockerfile: Dockerfile
